# Generated by Django 2.1 on 2018-10-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('conteudo', models.TextField(verbose_name='conteúdo')),
                ('data', models.DateField(verbose_name='Data')),
            ],
            options={
                'verbose_name': 'aula',
                'verbose_name_plural': 'aulas',
            },
        ),
    ]
