# Generated by Django 2.1 on 2018-10-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('pai', models.CharField(max_length=150, verbose_name='pai')),
                ('mae', models.CharField(max_length=150, verbose_name='mãe')),
                ('contato', models.CharField(max_length=150, verbose_name='número para contato')),
                ('datanascimento', models.DateField(verbose_name='data de nascimento')),
            ],
            options={
                'verbose_name': 'aluno',
                'verbose_name_plural': 'alunos',
            },
        ),
    ]
